theme: jekyll-theme-modernist
title: MEGAN GALBRAITH
description: >- # this means to ignore newlines until next ":"
  <a href="mailto:meg_galbraith@hotmail.com">meg_galbraith@hotmail.com</a><br>
  <a href="www.github.com/galbrame">www.github.com/galbrame</a><br>
  <a href="www.linkedin.com/in/megan-galbraith">www.linkedin.com/in/megan-galbraith</a>
