theme: jekyll-theme-modernist
title: MEGAN GALBRAITH
description: >- # this means to ignore newlines until next ":"
  <a href="mailto:meg_galbraith@hotmail.com">meg_galbraith@hotmail.com</a><br>
  <a href="https://www.github.com/galbrame" target="_blank" rel="noopener noreferrer">www.github.com/galbrame</a><br>
  <a href="https://www.linkedin.com/in/megan-galbraith" target="_blank" rel="noopener noreferrer">www.linkedin.com/in/megan-galbraith</a>
